---
title: "NOAC network meta-analysis: Bleeding"
author: "Benjamin Chan"
date: "`r Sys.time()`"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---


Clean up the data (do not show the code).

```{r, echo=FALSE}
D4 <- readSheet("Bleeding")
D4 <- tidyData(D4)
show(D4)
network <- mtc.network(D4[!is.na(responders)])
```

`Run the model using `r sprintf("%s-effects", effect)`.

```{r bleedingNetwork, results='hide'}
M <- mtc.model(network, type="consistency", linearModel=effect)
plot(M)
results <- mtc.run(M, n.adapt=nAdapt, n.iter=nIter, thin=thin)
```

# Summary

Direct and indirect odds ratios and 95% confidence bounds are stored in
[mtcBleedingOddsRatios.csv](mtcBleedingOddsRatios.csv).

```{r}
or <- combineResults()
write.csv(or, file="mtcBleedingOddsRatios.csv", row.names=FALSE)
show(or)
```

# Diagnostics

```{r}
summary(results)
```

Sampler diagnostics.

```{r bleedingGelman, fig.height=6}
gelman.plot(results)
gelman.diag(results)
```

```{r bleedingTrace, fig.height=8}
plot(results)
```

```{r bleedingAutocorr, fig.height=6}
autocorr.plot(results$samples)
```

Assess the degree of heterogeneity and inconsistency.

```{r, results='hide'}
anohe <- mtc.anohe(network, n.adapt=nAdapt, n.iter=nIter, thin=thin)
```

```{r bleedingAnohe, fig.height=6}
summary(anohe)
plot(anohe)
```
