---
title: "NOAC network meta-analysis: Stroke"
author: "Benjamin Chan"
date: "`r Sys.time()`"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---


Clean up the data (do not show the code).

```{r, echo=FALSE}
D2 <- readSheet("Stroke")
D2 <- tidyData(D2)
show(D2)
network <- mtc.network(D2)
```

# Network plot

```{r strokeNetwork}
plot(network)
```

Run the model using `r sprintf("%s-effects", effect)`.

```{r, results='hide'}
M <- mtc.model(network, type="consistency", linearModel=effect)
runtime <- system.time(results <- mtc.run(M, n.adapt=nAdapt, n.iter=nIter, thin=thin))
```

# Summary

Direct and indirect odds ratios and 95% confidence bounds are stored in
[mtcStrokeOddsRatios.csv](mtcStrokeOddsRatios.csv).

```{r}
or <- combineResults()
write.csv(or, file="mtcStrokeOddsRatios.csv", row.names=FALSE)
show(or)
```

# Diagnostics

```{r}
runtime
summary(results)
```

Sampler diagnostics.

```{r strokeGelman, fig.height=8}
gelman.plot(results)
gelman.diag(results)
```

```{r strokeTrace, fig.height=10}
plot(results)
```

Assess the degree of heterogeneity and inconsistency.

```{r, results='hide'}
anohe <- mtc.anohe(network, n.adapt=nAdapt, n.iter=nIter, thin=thin)
```

```{r strokeAnohe, fig.height=8}
summary(anohe)
plot(anohe)
```
